title: Claire Eats
theme: minima
collections:
  food:
    output: true


defaults:
  - scope:
      type: "food"
    values:
      layout: meal


header_files:
  - about.md
  - breakfast.md
  - lunch.md
  - dinner.md
