title: Claire Eats
author: Claire Hubble, © 2025
theme: minima
collections:
  food:
    output: true


defaults:
  - scope:
      type: "food"
    values:
      layout: meal


header_pages:
  - about.md
  - breakfast.md
  - lunch.md
  - dinner.md

